<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    

<?= $this->inlineScript()
->prependFile($this->basePath('js/bootstrap.min.js'))
->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>

</head>
<body>

<div class="container">
<?= $this->content ?>
</div>


</body>
</html>
