<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">Países</div>
            <div class="card-body">
                <table id="tabelaMedalhasPais" class="table">
                    <thead>
                        <tr>
                            <th scope="col">País</th>
                            <th scope="col">Ouro</th>
                            <th scope="col">Prata</th>
                            <th scope="col">Bronze</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">Atletas</div>
            <div class="card-body">
                <table id="tabelaMedalhasAtletas" class="table">
                    <thead>
                        <tr>
                            <th scope="col">Atleta</th>
                            <th scope="col">Ouro</th>
                            <th scope="col">Prata</th>
                            <th scope="col">Bronze</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>